### ISSUE TITLE
Localisations

### ISSUE THREAD

**Issue by cortig** [graphsketcher/GraphSketcher#3] opened 2014-01-22 00:09 UTC
(Following up on a Twitter message now that I found the GitHub project page)

The current build of GraphSketcher doesn't have any resources for languages other than English.

Now… the current build is localizable (editable .nib, yeah!!), so I took the opportunity to work on an update for the old French localization.
All .strings and .nib are now ready, but the HTML files are not done yet.
There is also a PDF file with a list of shortcut. I can't currently localize it without having the source document that has been used to generate it.

The thing is though that I'm not too familiar with GitHub, and especially when it comes to committing a localization.
Any suggestion?

**Comment by correia** [comment] 2014-01-28 17:13
Duplicate of issue #3.

**Closed as completed by correia** 2014-01-28 17:13 UTC
Labels: duplicate
